# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "Start seeds"
Package.delete_all
Package.create([
    {
      "supplier": "Visual",
      "destination": "Porto Seguro",
      "name": "Belezas de porto seguro",
      "id_post": 6764,
      "id_url": "id1101",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/porto-seguro-visual-id1101/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/08/Arraial-dAjuda-550x550.jpg",
      "duration_days": 8,
      "price_min_brl": 2253,
      "price_max_brl": nil,
      "accept_parcels": false,
      "parcels_amount": 1,
      "summary": "7 noites em Porto Seguro, voos saindo de Ribeirão Preto e transfers incluídos, passeios à sua escolha.",
      "departure_location": "Riberão Preto",
      "is_flexible": true,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "history, explorer, on_budget, sea",
      "services": "flight, breakfast, hospitality, city_tour, activities, transferts_airport"
    },
    {
      "supplier": "Viagens Promo",
      "destination": "Porto Seguro",
      "name": "Viva Porto Seguro",
      "id_post": 6790,
      "id_url": "id2202",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/viva-porto-seguro-vp-id2202/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/08/IMG_9966-550x550.jpg",
      "duration_days": 8,
      "price_min_brl": 3666,
      "price_max_brl": nil,
      "accept_parcels": true,
      "parcels_amount": 10,
      "summary": "7 noites em Porto Seguro, voos saindo de São Paulo e transfers incluídos, passeios à sua escolha.",
      "departure_location": "São Paulo",
      "is_flexible": false,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "history, explorer, on_budget, sea",
      "services": "flight, breakfast, hospitality, city_tour, activities, transferts_airport"
    },
    {
      "supplier": "Viagens Promo",
      "destination": "Porto Seguro",
      "name": "Porto Seguro All-inclusive",
      "id_post": 6807,
      "id_url": "id2203",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/porto-seguro-all-inclusive-vp-id2203/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/08/IMG_7945-1-550x550.jpg",
      "duration_days": 8,
      "price_min_brl": 6790,
      "price_max_brl": nil,
      "accept_parcels": true,
      "parcels_amount": 10,
      "summary": "7 noites em resort All-inclusive na praia, voos saindo de São Paulo e transfers incluídos.",
      "departure_location": "São Paulo",
      "is_flexible": false,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "history, explorer, family, sea",
      "services": "flight, all-inclusive, hospitality, city_tour, activities, transferts_airport, breakfast, meals"
    },
    {
      "supplier": "Viagens Promo",
      "destination": "Porto Seguro",
      "name": "A joia d'Arraia d'Ajuda",
      "id_post": 6812,
      "id_url": "id2204",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/joia-arraial-d-ajuda-vp-id2204/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/08/pexels-caico-gontijo-3343241-6134356-550x550.jpg",
      "duration_days": 8,
      "price_min_brl": 3590,
      "price_max_brl": nil,
      "accept_parcels": true,
      "parcels_amount": 10,
      "summary": "7 noites em Arraia D'Ajuda, voos saindo de São Paulo e transfers incluídos, passeios à sua escolha.",
      "departure_location": "São Paulo",
      "is_flexible": false,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "history, explorer, on_budget, sea",
      "services": "flight, breakfast, hospitality, city_tour, activities, transferts_airport"
    },
    {
      "supplier": "Viagens Promo",
      "destination": "Porto Seguro",
      "name": "Porto Seguro via VP Air",
      "id_post": 6846,
      "id_url": "id301",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/voo-porto-seguro-vpair-id301/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/08/pexels-tarik-nachat-28300-112116-550x550.jpg",
      "duration_days": 8,
      "price_min_brl": 1720,
      "price_max_brl": nil,
      "accept_parcels": true,
      "parcels_amount": 10,
      "summary": "Voos Ida e Volta, São Paulo - Porto Seguro via VP Air. Condições excepcionais em Janeiro 2025.",
      "departure_location": "São Paulo",
      "is_flexible": false,
      "validity_start": "01/01/2025",
      "validity_end": "31/01/2025",
      "themes": "history, explorer, sea, flight",
      "services": "flight"
    },
    {
      "supplier": "Visual",
      "destination": "New York",
      "name": "Magia da Nova Iorque",
      "id_post": 6627,
      "id_url": "",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/magia-de-nova-iorque-visual/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/06/NYC-Visual-550x550.jpg",
      "duration_days": 6,
      "price_min_brl": 11300,
      "price_max_brl": nil,
      "accept_parcels": false,
      "parcels_amount": 1,
      "summary": "6 cinco dias de descobertas fascinantes no coração da cidade que nunca dorme. Visite a icônica Estátua da Liberdade, explore a vida noturna vibrante de Manhattan, conheça a historia de Ellis Island e assista a um show na icônica Broadway.",
      "departure_location": nil,
      "is_flexible": true,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "urban, romantic, luxe, premium, nigthlife, explorer, cultural",
      "services": ""
    },
    {
      "supplier": "None",
      "destination": "Tampa Bay",
      "name": "Good Vibes em Tampa",
      "id_post": 6604,
      "id_url": "",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/tampa-good-vibes-ep/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/05/IMG_6024-550x550.jpeg",
      "duration_days": 6,
      "price_min_brl": nil,
      "price_max_brl": nil,
      "accept_parcels": false,
      "parcels_amount": 1,
      "summary": "Sinta as Boas Vibrações de Tampa: Uma Mistura de Aventura, Diversão e Gastronomia!",
      "departure_location": nil,
      "is_flexible": true,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "urban, explorer, sea, nightlife, cultural",
      "services": "breakfast, hospitality"
    },
    {
      "supplier": "None",
      "destination": "Tampa Bay",
      "name": "Tampa com a familia",
      "id_post": 6578,
      "id_url": "",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/familia-tampa-bay/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/05/pexels-rickyrecap-1868861-550x550.jpg",
      "duration_days": 6,
      "price_min_brl": nil,
      "price_max_brl": nil,
      "accept_parcels": false,
      "parcels_amount": 1,
      "summary": "Com uma mistura de aventura, entretenimento e diversão, Tampa Bay é o lugar perfeito para criar memórias inesquecíveis com aqueles que amamos.",
      "departure_location": nil,
      "is_flexible": true,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "family, sea, explorer, kids, cultural",
      "services": "breakfast, hospitality"
    },
    {
      "supplier": "Travel Gourmet",
      "destination": "França",
      "name": "Rotas da Borgonha",
      "id_post": 7032,
      "id_url": "id10503",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/rotas-borgonha-tg-id10503/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/10/pexels-pixabay-51947-550x550.jpg",
      "duration_days": 8,
      "price_min_brl": 21000,
      "price_max_brl": nil,
      "accept_parcels": true,
      "parcels_amount": 10,
      "summary": "Em 8 dias, descubra a rica herança vinícola e gastronômica da Borgonha, explorando os vinhedos renomados de Beaune e Côte d'Or, castelos históricos e saboreando a culinária francesa em sua melhor forma.",
      "departure_location": nil,
      "is_flexible": true,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "experience, explorer, gastronomic, luxe, premium, countryside, romantic",
      "services": "hospitality, city_tour, activities, transferts_airport, breakfast, meals, degustations, aulas, transferts, local_guide_pt"
    },
    {
      "supplier": "Travel Gourmet",
      "destination": "França",
      "name": "Bordeaux, coração gastronomico",
      "id_post": 7011,
      "id_url": "id10502",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/bordeaux-gastronomico-id10502/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/10/vineyard-5810650-550x550.jpg",
      "duration_days": 8,
      "price_min_brl": 21000,
      "price_max_brl": nil,
      "accept_parcels": true,
      "parcels_amount": 10,
      "summary": "8 dias pela região de Bordeaux e Périgord, combinando a descoberta de vinhos prestigiados, trufas e foie gras, com visitas a vilarejos medievais, castelos e atividades ao ar livre, incluindo degustações exclusivas e experiências culinárias com grandes chefs.",
      "departure_location": nil,
      "is_flexible": true,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "experience, explorer, gastronomic, luxe, premium, countryside, romantic",
      "services": "hospitality, city_tour, activities, transferts_airport, breakfast, meals, degustations, aulas, transferts, local_guide_pt"
    },
    {
      "supplier": "Travel Gourmet",
      "destination": "França",
      "name": "O perfume da Provence",
      "id_post": 6983,
      "id_url": "id10501",
      "status": "Online",
      "url": "https://place-trip.com/tour-item/o-perfume-da-provence-id10501/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/10/pexels-hkubrakisa-17591210-550x550.jpg",
      "duration_days": 8,
      "price_min_brl": 21000,
      "price_max_brl": nil,
      "accept_parcels": true,
      "parcels_amount": 10,
      "summary": "8 dias no Perfume da Provence, a região mais colorida da França. Famosa para sua gastronomie, mergulha nas sabores do Sul da França com as degustações dos produtos locais, as aulas com os chefs franceses e as visitas do patrimonio exceptional.",
      "departure_location": nil,
      "is_flexible": true,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "experience, explorer, gastronomic, luxe, premium, countryside, romantic",
      "services": "hospitality, city_tour, activities, transferts_airport, breakfast, meals, degustations, aulas, transferts, local_guide_pt"
    },
    {
      "supplier": "Travel Gourmet",
      "destination": "França",
      "name": "Delicias de Paris",
      "id_post": 7040,
      "id_url": "id10501",
      "status": "Draft",
      "url": "",
      "img_url": "",
      "duration_days": "",
      "price_min_brl": "",
      "price_max_brl": "",
      "accept_parcels": "",
      "parcels_amount": "",
      "summary": "",
      "departure_location": "",
      "is_flexible": "",
      "validity_start": "",
      "validity_end": "",
      "themes": "",
      "services": ""
    },
    {
      "supplier": "CT Operadora",
      "destination": "Indonesia & Bali",
      "name": "O melhor da Bali",
      "id_post": 6930,
      "id_url": "id10401",
      "status": "Draft",
      "url": "https://place-trip.com/tour-item/melhor-de-bali-ct-id10401/ ‎",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/09/pexels-aronvisuals-1643130-550x550.jpg",
      "duration_days": 7,
      "price_min_brl": 15500,
      "price_max_brl": nil,
      "accept_parcels": false,
      "parcels_amount": 1,
      "summary": "7 dias excepcionais entre templos sagrados, praias paradisíacas e gastronomia típica. O melhor de Bali está aqui.",
      "departure_location": nil,
      "is_flexible": true,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "explorer, sea, nightlife, cultural, to_relax, history, romantic, premium, luxe",
      "services": "breakfast, hospitality, city_tour, activities, transferts_airport"
    },
    {
      "supplier": "CT Operadora",
      "destination": "Indonesia & Bali",
      "name": "Maravilhosa Indonésia",
      "id_post": 6954,
      "id_url": "id10401",
      "status": "Draft",
      "url": "https://place-trip.com/tour-item/maravilhosa-indonesia-ct-id10402/",
      "img_url": "https://place-trip.com/wp-content/uploads/2024/09/pexels-aronvisuals-1646870-550x550.jpg",
      "duration_days": 8,
      "price_min_brl": nil,
      "price_max_brl": nil,
      "accept_parcels": false,
      "parcels_amount": 1,
      "summary": "8 dias a mergulhar na cultura milenar, na natureza exuberante e na espiritualidade da Maravilha Indonesia.",
      "departure_location": nil,
      "is_flexible": true,
      "validity_start": nil,
      "validity_end": nil,
      "themes": "explorer, sea, nightlife, cultural, to_relax, history, romantic, premium, luxe",
      "services": "breakfast, hospitality, city_tour, activities, transferts_airport"
    }
  ])